### ISSUE TITLE
As of 2023.4.3 the m-e-row shows status of people as raw home/not_home instead of Home/Away

### ISSUE THREAD

**Issue by wigster** [benct/lovelace-multiple-entity-row#292]
After upgrade to 2023.4.3 from 2023.4.2, the status of people is being shown as home/not_home (the real state string) and not the friendly version. 

![image](https://user-images.githubusercontent.com/10956987/231694694-1e76cec3-e451-4dcd-96c3-d49baf57cc0f.png)

**Comment by aksnet** [comment]
This seems to be the same issue for battery values, see:
When custom:multiple-entity-row is used the value switches to english instead of german.
![2023-04-13 13_26_14-Übersicht – Home Assistant](https://user-images.githubusercontent.com/27338153/231745310-81f1454b-cc5c-4723-ae94-7238944bf91c.png)

**Comment by ildar170975** [comment]
Confirmed, 2023.4.4 (worked fine in 2023.4.0)

**Comment by Anton-Ka** [comment]
> В версии 2023.4 получена высокая доступность высокой скорости записи и имени, поэтому ключи записи состояния объекта также изменились. ComputeStateDisplay в этом репозитории его устарел, и необходимо обновить с помощью новых клавиш.
> 
> https://github.com/home-assistant/frontend/blob/dev/src/common/entity/compute_state_display.ts

Should something be done about this, or will it be fixed in an update?

**Comment by sheminasalam** [comment]
Problem persists with my door binary sensors even after updates.
![image](https://user-images.githubusercontent.com/45196177/232235030-6c72b5a2-145d-4401-8027-d2bddb99c98d.png)

**Comment by SAOPP** [comment]
This issue is present everywhere, where I use binary sensors and m-e-row card.

**Comment by alexruffell** [comment]
Same here! I use this extensively on my dashboards so now they are all broken :(

**Comment by Fierys** [comment]
Yes, it doesn't look very nice. what to do with it? should i wait for the update?
![image_2023-04-16_20-31-45](https://user-images.githubusercontent.com/13329786/232395586-f724b120-21da-41ad-a6ce-a759261e4fa5.png)

**Comment by mill1000** [comment]
> With 2023.4, HA core added support for translations attributes and name so entity state translation keys have changed too. The computeStateDisplay in this repository is outdated and need to be updated with new translation keys.
> 
> https://github.com/home-assistant/frontend/blob/dev/src/common/entity/compute_state_display.ts

@piitaya I've seen similar issues in other custom cards due to out-of-date or homebrewed localization. Is there anyway to access the computeStateDisplay from the frontend itself?

**Comment by sheminasalam** [comment]
any updates

**Comment by GRClark** [comment]
Is there any progress on this?  Love the integration but not sure whether I should bite the bullet upgrading and change all my dashboard code or hold off in hopes this will be fixed.

**Comment by GRClark** [comment]
> any updates

There’s a pull request but that was a month ago.  Not sure how long it takes to become a published update.  

https://github.com/benct/lovelace-multiple-entity-row/pull/293

**Comment by mill1000** [comment]
Those looking for a quick solution can add my fork as a custom repo under HACs. See here: https://github.com/benct/lovelace-multiple-entity-row/pull/293#issuecomment-1559725690

**Comment by alexruffell** [comment]
@mill1000 Thank you for sharing and making it easy for all to fix the issue while we wait on the original developer/maintainer to merge your PR.

**Comment by GRClark** [comment]
> Those looking for a quick solution can add my fork as a custom repo under HACs. See here: [#293 (comment)](https://github.com/benct/lovelace-multiple-entity-row/pull/293#issuecomment-1559725690)

@mill1000 should we remove the previous multiple entity row integration from HACS before/also?  

Really appreciation you doing this and coming to the rescue!

**Comment by alexruffell** [comment]
@GRClark I left everything as it was and simply added the new repository. As soon as I did that, the updated integration appeared in a green box and I hit download. Problem was fixed. I left the original one in case the original developer resumes updating it.

**Comment by benct** [comment]
Pushed a new release containing the fix from @mill1000, as well as some other PRs. I'm not on the latest HA yet, so let me know if something is wrong.

**Comment by SAOPP** [comment]
@benct working as expected! Thanks homie!
